local _, M = ...
-- Monstrator's native database. Data\Native\*.lua register one compact tab-separated string per entity
-- (generated by tools\monstrator-db.cjs import). Rows are decoded on demand and cached weakly, so only
-- what the UI touches is ever expanded into tables. Spawns are already keyed by UiMap ID.
-- Data\Native\Overlay.lua (generated by tools\monstrator-db.cjs overlay) replaces or deletes base rows with
-- Monstrator's own corrections and harvested Forever discoveries; each overlaid row records its origin.

M.native = M.native or { data = {}, meta = {} }
M.native.overlay = M.native.overlay or {}
M.native.origin = M.native.origin or {}

-- source names where imported base rows came from (recorded for attribution); nil = Monstrator's own.
function M.NativeData(kind, version, flavor, commit, source)
    local native = M.native
    native.data[kind] = native.data[kind] or {}
    native.meta[kind] = { version = tostring(version), flavor = flavor, commit = commit, source = source }
    native.provider = nil
    return native.data[kind]
end

-- Returns (rows, origins): rows[id] = full replacement row, or false to delete the base entity.
function M.NativeOverlay(kind)
    local native = M.native
    native.overlay, native.origin = native.overlay or {}, native.origin or {}
    native.overlay[kind] = native.overlay[kind] or {}
    native.origin[kind] = native.origin[kind] or {}
    native.provider = nil
    return native.overlay[kind], native.origin[kind]
end

local function split(text)
    local fields, n = {}, 0
    for value in (text .. "\t"):gmatch("([^\t]*)\t") do n = n + 1; fields[n] = value end
    return fields
end

local function idList(text)
    if not text or text == "" then return nil end
    local list = {}
    for id in text:gmatch("%d+") do list[#list + 1] = tonumber(id) end
    return list
end

local function number(text)
    return text and text ~= "" and tonumber(text) or nil
end

local function text(value)
    return value ~= "" and value or nil
end

local function spawns(field)
    if not field or field == "" then return nil end
    local result = {}
    for mapID, points in field:gmatch("(%d+):([^;]*)") do
        local list = {}
        for x, y in points:gmatch("([%d%.eE%-]+),([%d%.eE%-]+)") do list[#list + 1] = { tonumber(x), tonumber(y) } end
        result[tonumber(mapID)] = list
    end
    return result
end

local function mapIDs(field)
    if not field or field == "" then return nil end
    local result = {}
    for mapID in field:gmatch("(%d+):") do result[tonumber(mapID)] = true end
    return result
end

-- Builds one lib-shaped table per entity kind; every getter takes an ID and returns nil when absent.
local function table_for(data, layout, overlay, origin)
    overlay, origin = overlay or {}, origin or {}
    local cache = setmetatable({}, { __mode = "v" })
    local ids
    local function raw(id)
        local value = overlay[id]
        if value == false then return nil end
        return value or data[id]
    end
    local function row(id)
        local cached = cache[id]
        if cached then return cached end
        local text = raw(id)
        if not text then return nil end
        cached = split(text)
        cache[id] = cached
        return cached
    end
    local api = {
        GetAllIds = function()
            if not ids then
                ids = {}
                for id in pairs(data) do if overlay[id] ~= false then ids[#ids + 1] = id end end
                for id, value in pairs(overlay) do
                    if value and not data[id] then ids[#ids + 1] = id end
                end
                table.sort(ids)
            end
            return ids
        end,
        Has = function(id) return raw(id) ~= nil end,
        -- "discovery" or "correction" for overlaid rows, nil for unmodified base rows.
        Origin = function(id) return overlay[id] ~= nil and origin[id] or nil end,
    }
    for name, spec in pairs(layout) do
        local index, decode = spec[1], spec[2]
        api[name] = function(id)
            local fields = row(id)
            if fields then return decode(fields[index]) end
        end
    end
    return api
end

local faction = function(value) return value ~= "" and value or nil end
local identityMap = setmetatable({}, { __index = function(_, key) return key end })

function M:NativeProvider()
    local native = self.native
    if native.provider then return native.provider end
    native.overlay, native.origin = native.overlay or {}, native.origin or {}
    -- A build without imported base data still serves Monstrator's own overlay (discoveries, corrections).
    local npcs, own = native.data.Npc, native.overlay.Npc
    if not (npcs and next(npcs)) and not (own and next(own)) then return nil end
    local meta = native.meta.Npc or { version = "local", flavor = "Forever" }
    local function tableOf(kind, layout)
        return table_for(native.data[kind] or {}, layout, native.overlay[kind], native.origin[kind])
    end
    local lib = {
        native = true, addonName = "Monstrator", version = meta.version, flavor = meta.flavor,
        commit = meta.commit, source = meta.source, imported = (npcs and next(npcs)) and true or false,
        areaMap = identityMap,
        Npc = tableOf("Npc", {
            name = { 1, text }, subName = { 2, text }, npcFlags = { 3, number }, minLevel = { 4, number },
            maxLevel = { 5, number }, friendlyToFaction = { 6, faction }, spawns = { 7, spawns }, mapIDs = { 7, mapIDs },
        }),
    }
    if native.data.Object or native.overlay.Object then
        lib.Object = tableOf("Object", { name = { 1, text }, spawns = { 2, spawns }, mapIDs = { 2, mapIDs }, class = { 3, text } })
    end
    if native.data.Item or native.overlay.Item then
        lib.Item = tableOf("Item", {
            name = { 1, text }, requiredLevel = { 2, number }, itemLevel = { 3, number }, class = { 4, number },
            subClass = { 5, number }, startQuest = { 6, number }, vendors = { 7, idList }, npcDrops = { 8, idList },
            objectDrops = { 9, idList }, questRewards = { 10, idList }, itemDrops = { 11, idList },
        })
        local reference = native.lootReference
        if reference then
            local baseDrops = lib.Item.npcDrops
            local function additionalDrops(id)
                if not lib.Item.Has(id) or lib.Item.Origin(id) then return {} end
                local existing, result = {}, {}
                for _, npcID in ipairs(baseDrops(id) or {}) do existing[npcID] = true end
                for _, npcID in ipairs(idList(reference.drops[id]) or {}) do
                    if not existing[npcID] and lib.Npc.Has(npcID) then
                        result[#result + 1] = npcID
                        existing[npcID] = true
                    end
                end
                return result
            end
            lib.Item.npcDrops = function(id)
                local base, extra = baseDrops(id), additionalDrops(id)
                if #extra == 0 then return base end
                local result = {}
                for _, npcID in ipairs(base or {}) do result[#result + 1] = npcID end
                for _, npcID in ipairs(extra) do result[#result + 1] = npcID end
                return result
            end
            lib.Item.npcDropReference = function(id, npcID)
                for _, ref in ipairs(additionalDrops(id)) do
                    if ref == npcID then return reference.source end
                end
            end
        end
    end
    if native.data.Quest or native.overlay.Quest then
        local quest = tableOf("Quest", {
            name = { 1, text }, questLevel = { 2, number }, requiredLevel = { 3, number },
            starterNpcs = { 4, idList }, starterObjects = { 5, idList },
            finisherNpcs = { 6, idList }, finisherObjects = { 7, idList },
        })
        quest.startedBy = function(id)
            if not quest.Has(id) then return nil end
            return { quest.starterNpcs(id), quest.starterObjects(id) }
        end
        quest.finishedBy = function(id)
            if not quest.Has(id) then return nil end
            return { quest.finisherNpcs(id), quest.finisherObjects(id) }
        end
        lib.Quest = quest
    end
    native.provider = lib
    return lib
end

function M:NativeSummary()
    local native, counts = self.native, {}
    for kind, data in pairs(native.data) do
        local n = 0
        for _ in pairs(data) do n = n + 1 end
        counts[kind] = n
    end
    local overlays = {}
    for kind, rows in pairs(native.overlay or {}) do
        for id, value in pairs(rows) do
            local origin = value == false and "deleted" or (native.origin or {})[kind] and native.origin[kind][id] or "correction"
            overlays[origin] = (overlays[origin] or 0) + 1
            if value and not (native.data[kind] and native.data[kind][id]) then counts[kind] = (counts[kind] or 0) + 1
            elseif value == false and native.data[kind] and native.data[kind][id] then counts[kind] = counts[kind] - 1 end
        end
    end
    return counts, native.meta.Npc, overlays
end
