-- Monstrator native overlay. GENERATED by tools\monstrator-db.cjs overlay from Data\Source\Discoveries.lua
-- and Data\Source\Corrections.lua. Each row replaces (or with false, deletes) the base row of the same ID.
local _, M = ...
do local D, O = M.NativeOverlay("Npc")
D[8361]="Chepi	Reagent Vendor	4	30	30	H	1456:36.38,54.85 37.39,51.76" O[8361]="discovery"
D[277055]="Axle Smoothslice		0				1456:35.73,54.51" O[277055]="discovery"
end
